<?php
# This file was automatically generated by the MediaWiki 1.46.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "حاکمیت اطلاعات و فرآیندهای آموزشی (حافا)";
$wgMetaNamespace = "حاکمیت_اطلاعات_و_فرآیندهای_آموزشی_(حافا)";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://wiki";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/hafa.png",
	'icon' => "$wgResourceBasePath/resources/assets/hafa.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "Hafa_wiki";
$wgDBuser = "root";
$wgDBpassword = "Reza@123";

# MySQL specific settings
$wgDBprefix = "hafa";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgFileExtensions = array_values( array_unique( array_merge(
    $wgFileExtensions,
    [ 'pdf', 'png', 'jpg', 'jpeg', 'svg', 'bpmn' ]
) ) );
$wgMaxUploadSize = 20 * 1024 * 1024; // 20 MiB

#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/Languages/Data/Names.php
$wgLanguageCode = "fa";

# Time zone
$wgLocaltimezone = 'Asia/Tehran';
// $wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "8b6306cb6023bd7dc6d20d330f00357b2d1fbd2a14a79861b4931687b326eb2f";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "7a2614538a893e15";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions["*"]["createaccount"] = false;
$wgGroupPermissions["*"]["edit"] = false;
$wgGroupPermissions["*"]["read"] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "monobook";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Mermaid' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'PageForms' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SemanticMediaWiki' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );


# End of automatically generated settings.
# Add more configuration options below.

# فضاهای نام حافا. قبل از استفاده، از آزاد بودن شناسه‌ها در تنظیمات فعلی اطمینان یابید.
define( 'NS_HAFA_PROCESS', 3080 );
define( 'NS_HAFA_ACTIVITY', 3082 );
define( 'NS_HAFA_SYSTEM', 3084 );
define( 'NS_HAFA_TERM', 3086 );
define( 'NS_HAFA_DATA', 3088 );
define( 'NS_HAFA_NEED', 3090 );
define( 'NS_HAFA', 3092 );
define( 'NS_HAFA_CAPABILITY', 3094 );
define( 'NS_HAFA_GAP', 3096 );

$wgExtraNamespaces[NS_HAFA_PROCESS] = 'فرآیند';
$wgExtraNamespaces[NS_HAFA_PROCESS + 1] = 'بحث_فرآیند';
$wgExtraNamespaces[NS_HAFA_ACTIVITY] = 'فعالیت';
$wgExtraNamespaces[NS_HAFA_ACTIVITY + 1] = 'بحث_فعالیت';
$wgExtraNamespaces[NS_HAFA_SYSTEM] = 'سامانه';
$wgExtraNamespaces[NS_HAFA_SYSTEM + 1] = 'بحث_سامانه';
$wgExtraNamespaces[NS_HAFA_TERM] = 'واژه';
$wgExtraNamespaces[NS_HAFA_TERM + 1] = 'بحث_واژه';
$wgExtraNamespaces[NS_HAFA_DATA] = 'داده';
$wgExtraNamespaces[NS_HAFA_DATA + 1] = 'بحث_داده';
$wgExtraNamespaces[NS_HAFA_NEED] = 'نیاز';
$wgExtraNamespaces[NS_HAFA_NEED + 1] = 'بحث_نیاز';
$wgExtraNamespaces[NS_HAFA] = 'حافا';
$wgExtraNamespaces[NS_HAFA + 1] = 'بحث_حافا';
$wgExtraNamespaces[NS_HAFA_CAPABILITY] = 'قابلیت';
$wgExtraNamespaces[NS_HAFA_CAPABILITY + 1] = 'بحث_قابلیت';
$wgExtraNamespaces[NS_HAFA_GAP] = 'شکاف';
$wgExtraNamespaces[NS_HAFA_GAP + 1] = 'بحث_شکاف';

foreach ( [ NS_HAFA_PROCESS, NS_HAFA_ACTIVITY, NS_HAFA_SYSTEM, NS_HAFA_TERM, NS_HAFA_DATA, NS_HAFA_NEED, NS_HAFA ] as $hafaNamespace ) {
    $wgNamespacesWithSubpages[$hafaNamespace] = true;
}

# گروه‌های نقش حافا. جزئیات نهایی دسترسی در صفحه «حافا: معماری ابزار و سطوح دسترسی» تصویب شود.
$wgGroupPermissions['hafa-contributor']['read'] = true;
$wgGroupPermissions['hafa-contributor']['edit'] = true;
$wgGroupPermissions['hafa-contributor']['createpage'] = true;
$wgGroupPermissions['hafa-contributor']['upload'] = true;
$wgGroupPermissions['hafa-unit-representative'] = $wgGroupPermissions['hafa-contributor'];
$wgGroupPermissions['hafa-reviewer'] = $wgGroupPermissions['hafa-contributor'];
$wgGroupPermissions['hafa-wiki-steward'] = $wgGroupPermissions['hafa-reviewer'];
$wgGroupPermissions['hafa-wiki-steward']['editinterface'] = true;
$wgGroupPermissions['hafa-wiki-steward']['move'] = true;

# حساب فقط توسط مدیر ویکی ساخته می‌شود؛ حساب مشترک ممنوع است.
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['sysop']['createaccount'] = true;

# محدودسازی صفحات ساختاری؛ فقط مدیران و راهبر ویکی مجاز به ویرایش‌اند.
$wgGroupPermissions['hafa-wiki-steward']['editprotected'] = true;
$wgGroupPermissions['sysop']['editprotected'] = true;

# حساب اختصاصی ورود گروهی؛ از sysop استفاده نشود.
$wgGroupPermissions['hafa-importer']['read'] = true;
$wgGroupPermissions['hafa-importer']['edit'] = true;
$wgGroupPermissions['hafa-importer']['createpage'] = true;
$wgGroupPermissions['hafa-importer']['import'] = true;
$wgGroupPermissions['hafa-importer']['importupload'] = true;
$wgGroupPermissions['hafa-importer']['upload'] = true;

# افزونه‌های اختیاری: فقط بعد از نصب واقعی و اجرای update.php، خطوط مربوط را فعال کنید.
# wfLoadExtension( 'ApprovedRevs' );
# wfLoadExtension( 'ConfirmEdit' );
# wfLoadExtension( 'AbuseFilter' );
# wfLoadExtension( 'OATHAuth' );

# توجه: مقدار قبلی $smwgEditProtectionRight = false را حذف کنید،
# مگر آنکه نیاز و اثر آن در نسخه نصب‌شده Semantic MediaWiki آزموده شده باشد.

# مدیر دسترسی حافا: فقط مدیریت عضویت کاربران در گروه‌های عملیاتی حافا
$wgGroupPermissions['hafa-access-manager']['read'] = true;
$wgGroupPermissions['hafa-access-manager']['userrights'] = true;

# فهرست گروه‌هایی که مدیر دسترسی حافا اجازه انتساب/حذف آن‌ها را دارد
$hafaAssignableGroups = [
    'hafa-contributor',
    'hafa-unit-representative',
    'hafa-reviewer',
    'hafa-wiki-steward',
    'hafa-importer',
];

# مدیر دسترسی حافا فقط مجاز به مدیریت گروه‌های فهرست بالاست
$wgAddGroups['hafa-access-manager'] = $hafaAssignableGroups;
$wgRemoveGroups['hafa-access-manager'] = $hafaAssignableGroups;

# گروه «دیوان‌سالار» در رابط فارسی، همان bureaucrat در تنظیمات است
$wgAddGroups['bureaucrat'] = array_merge(
    $wgAddGroups['bureaucrat'] ?? [],
    array_merge( $hafaAssignableGroups, [ 'hafa-access-manager' ] )
);

$wgRemoveGroups['bureaucrat'] = array_merge(
    $wgRemoveGroups['bureaucrat'] ?? [],
    array_merge( $hafaAssignableGroups, [ 'hafa-access-manager' ] )
);

# ==============================
# اعطای موقت اختیار مدیریت کاربران به مدیران (sysop)
# فقط برای راه‌اندازی اولیه حافا
# ==============================

// $wgGroupPermissions['sysop']['userrights'] = true;

// $wgAddGroups['sysop'] = [
//     'hafa-contributor',
//     'hafa-unit-representative',
//     'hafa-reviewer',
//     'hafa-wiki-steward',
//     'hafa-importer',
//     'hafa-access-manager',
// ];

// $wgRemoveGroups['sysop'] = [
//     'hafa-contributor',
//     'hafa-unit-representative',
//     'hafa-reviewer',
//     'hafa-wiki-steward',
//     'hafa-importer',
//     'hafa-access-manager',
// ];